figure('name','Police','NumberTitle','off');
worldmap('india');
geoshow(states);
data = policedata(2011);
c = getcolor(data);
symbols = makesymbolspec('Polygon', ...
    {'NAME_1','Andhra Pradesh','FaceColor',[1,1,c(1)]}, ...
    {'NAME_1','Telangana','FaceColor',[1,1,c(1)]}, ...
    {'NAME_1','Arunachal Pradesh','FaceColor',[1,1,c(2)]}, ...
    {'NAME_1','Assam','FaceColor',[1,1,c(3)]}, ...
    {'NAME_1','Bihar','FaceColor',[1,1,c(4)]}, ...
    {'NAME_1','Chhattisgarh','FaceColor',[1,1,c(5)]}, ...
    {'NAME_1','Goa','FaceColor',[1,1,c(6)]}, ...
    {'NAME_1','Gujarat','FaceColor',[1,1,c(7)]}, ...
    {'NAME_1','Haryana','FaceColor',[1,1,c(8)]}, ...
    {'NAME_1','Himachal Pradesh','FaceColor',[1,1,c(9)]}, ...
    {'NAME_1','Jammu and Kashmir','FaceColor',[1,1,c(10)]}, ...
    {'NAME_1','Jharkhand','FaceColor',[1,1,c(11)]}, ...
    {'NAME_1','Karnataka','FaceColor',[1,1,c(12)]}, ...
    {'NAME_1','Kerala','FaceColor',[1,1,c(13)]}, ...
    {'NAME_1','Madhya Pradesh','FaceColor',[1,1,c(14)]}, ...
    {'NAME_1','Maharashtra','FaceColor',[1,1,c(15)]}, ...
    {'NAME_1','Manipur','FaceColor',[1,1,c(16)]}, ...
    {'NAME_1','Meghalaya','FaceColor',[1,1,c(17)]}, ...
    {'NAME_1','Mizoram','FaceColor',[1,1,c(18)]}, ...
    {'NAME_1','Nagaland','FaceColor',[1,1,c(19)]}, ...
    {'NAME_1','Orissa','FaceColor',[1,1,c(20)]}, ...
    {'NAME_1','Punjab','FaceColor',[1,1,c(21)]}, ...
    {'NAME_1','Rajasthan','FaceColor',[1,1,c(22)]}, ...
    {'NAME_1','Sikkim','FaceColor',[1,1,c(23)]}, ...
    {'NAME_1','Tamil Nadu','FaceColor',[1,1,c(24)]}, ...
    {'NAME_1','Tripura','FaceColor',[1,1,c(25)]}, ...
    {'NAME_1','Uttar Pradesh','FaceColor',[1,1,c(26)]}, ...
    {'NAME_1','Uttaranchal','FaceColor',[1,1,c(27)]}, ...
    {'NAME_1','West Bengal','FaceColor',[1,1,c(28)]}, ...
    {'NAME_1','Andaman and Nicobar','FaceColor',[1,1,c(29)]}, ...
    {'NAME_1','Chandigarh','FaceColor',[1,1,c(30)]}, ...
    {'NAME_1','Dadra and Nagar Haveli','FaceColor',[1,1,c(31)]}, ...
    {'NAME_1','Daman and Diu','FaceColor',[1,1,c(32)]}, ...
    {'NAME_1','Delhi UT','FaceColor',[1,1,c(33)]}, ...
    {'NAME_1','Lakshadweep','FaceColor',[1,1,c(34)]}, ...
    {'NAME_1','Puducherry','FaceColor',[1,1,c(35)]});
geoshow(states,'SymbolSpec',symbols, ...
    'DefaultFaceColor','blue','DefaultEdgeColor','black');