clear all;
clc;
year = (2001:2012);
data = xlsread('/home/negi/Documents/Matlab-Crime-Analysis/crimes_count_women_01_122.xls');
states = {'Andhra Pradesh','Arunachal Pradesh',...
    'Assam',...
    'Bihar',...
    'Chhattisgarh',...
    'Goa',...
    'Gujarat',...
    'Haryana',...
    'Himachal Pradesh',...
    'Jammu & Kashmir',...
    'Jharkhand',...
    'Karnataka',...
    'Kerala',...
    'Madhya Pradesh',...
    'Maharashtra',...
    'Manipur',...
    'Meghalaya',...
    'Mizoram',...
    'Nagaland',...
    'Odisha',...
    'Punjab',...
    'Rajasthan',...
    'Sikkim',...
    'Tamil Nadu',...
    'Tripura',...
    'Uttar Pradesh',...
    'Uttarakhand',...
    'West Bengal',...
    'A&N Islands',...
    'Chandigarh',...
    'D&N Haveli',...
    'Daman & Diu',...
    'Delhi UT',...
    'Lakshadweep',...
    'Puducherry'};

hFig = figure('name', '3D Plot of Crime', 'NumberTitle', 'off');
set(hFig, 'position', [700, 100, 1000, 1000]);
bar3(data,1);
xlabel('Years');
ylabel('States');
zlabel('Number of Cases');
set(gca, 'YTick', 1:35, 'YTickLabel', states, 'YTickLabelRotation', 30);
set(gca, 'position', [0.10 0.12 , 0.9, 0.9]);