function[state, type] = getstatetype(no1, no2);

states = {' Andhra Pradesh',' Arunachal Pradesh',...
    ' Assam',...
    ' Bihar',...
    ' Chhattisgarh',...
    ' Goa',...
    ' Gujarat',...
    ' Haryana',...
    ' Himachal Pradesh',...
    ' Jammu and Kashmir',...
    ' Jharkhand',...
    ' Karnataka',...
    ' Kerala',...
    ' Madhya Pradesh',...
    ' Maharashtra',...
    ' Manipur',...
    ' Meghalaya',...
    ' Mizoram',...
    ' Nagaland',...
    ' Orissa',...
    ' Punjab',...
    ' Rajasthan',...
    ' Sikkim',...
    ' Tamil Nadu',...
    ' Tripura',...
    ' Uttar Pradesh',...
    ' Uttarakhand',...
    ' West Bengal',...
    ' Andaman and Nicobar Islands',...
    ' Chandigarh',...
    ' Dadra and Nagar Haveli',...
    ' Daman and Diu',...
    ' Delhi',...
    ' Lakshadweep',...
    ' Puducherry',...
    ' Total'};
    
    types = {'Rapes','Kidnappings & Abductions', 'Dowry Deaths', 'Assaults','Insult to Modesty',...
    'Cruelty by Husband/Relatives',  'Immoral Traffic', 'Indescent Representation'};
 
end;