function[] = plots(state, type)

    %state is an integer value to denote the state
    %type is an integer value to denote the type of crime
    
    years = {'2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013'}; 
    data = xlsread('~/Documents/Matlab-Crime-Analysis/crimes_count_women_01_12.xls');
    
    states = {' Andhra Pradesh',' Arunachal Pradesh',...
    ' Assam',...
    ' Bihar',...
    ' Chhattisgarh',...
    ' Goa',...
    ' Gujarat',...
    ' Haryana',...
    ' Himachal Pradesh',...
    ' Jammu and Kashmir',...
    ' Jharkhand',...
    ' Karnataka',...
    ' Kerala',...
    ' Madhya Pradesh',...
    ' Maharashtra',...
    ' Manipur',...
    ' Meghalaya',...
    ' Mizoram',...
    ' Nagaland',...
    ' Orissa',...
    ' Punjab',...
    ' Rajasthan',...
    ' Sikkim',...
    ' Tamil Nadu',...
    ' Tripura',...
    ' Uttar Pradesh',...
    ' Uttarakhand',...
    ' West Bengal',...
    ' Andaman and Nicobar Islands',...
    ' Chandigarh',...
    ' Dadra and Nagar Haveli',...
    ' Daman and Diu',...
    ' Delhi',...
    ' Lakshadweep',...
    ' Puducherry',...
    ' Total'};
    
    types = {'Rapes','Kidnappings & Abductions', 'Dowry Deaths', 'Assaults','Insult to Modesty',...
    'Cruelty by Husband/Relatives',  'Immoral Traffic', 'Indescent Representation'};

    crime = data(36*(type-1)+state, 1:13);
    
    %figure ('name', 'Bar Graph')
    hFig = figure('name', 'Bar Graph', 'NumberTitle', 'off');   
    set(hFig, 'Position', [620 420 800 600])
    bar(crime);
    xlabel('\bf Year','FontSize', 15);
    ylabel('\bf No. of Cases', 'FontSize', 15);
    title(strcat(types(type),' in',states(state)), 'FontSize', 18);
    set(gca, 'XTick', 1:13, 'XTickLabel', years, 'XTickLabelRotation', 45);
    grid on
                
end