function[] = policeplots(state)

    %state is an integer value to denote the state
    %type is an integer value to denote the type of crime
    
    years = {'2001','2011'}; 
    data = xlsread('~/Documents/Topological_Crime_Analysis/Police/testing.xls');
    
    states = {' Andhra Pradesh',' Arunachal Pradesh',...
    ' Assam',...
    ' Bihar',...
    ' Chhattisgarh',...
    ' Goa',...
    ' Gujarat',...
    ' Haryana',...
    ' Himachal Pradesh',...
    ' Jammu and Kashmir',...
    ' Jharkhand',...
    ' Karnataka',...
    ' Kerala',...
    ' Madhya Pradesh',...
    ' Maharashtra',...
    ' Manipur',...
    ' Meghalaya',...
    ' Mizoram',...
    ' Nagaland',...
    ' Orissa',...
    ' Punjab',...
    ' Rajasthan',...
    ' Sikkim',...
    ' Tamil Nadu',...
    ' Tripura',...
    ' Uttar Pradesh',...
    ' Uttarakhand',...
    ' West Bengal',...
    ' Andaman and Nicobar Islands',...
    ' Chandigarh',...
    ' Dadra and Nagar Haveli',...
    ' Daman and Diu',...
    ' Delhi',...
    ' Lakshadweep',...
    ' Puducherry'};
    states = sort(states);

    crime = data(state, 1:2);
    
    %figure ('name', 'Bar Graph')
    hFig = figure('name', 'Bar Graph', 'NumberTitle', 'off');   
    set(hFig)
    bar(crime);
    xlabel('\bf Year','FontSize', 15);
    ylabel('\bf Count', 'FontSize', 15);
    title(strcat('Police strength in',states(state)), 'FontSize', 18);
    set(gca, 'XTick',1:11 , 'XTickLabel', years, 'XTickLabelRotation', 45);
    grid on
          